/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/activities/activity-list`; params?: Router.UnknownInputParams; } | { pathname: `/activities/add-activity`; params?: Router.UnknownInputParams; } | { pathname: `/activities/assessment-detail`; params?: Router.UnknownInputParams; } | { pathname: `/activities/evaluation-form`; params?: Router.UnknownInputParams; } | { pathname: `/activities/results`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/categories/add-category`; params?: Router.UnknownInputParams; } | { pathname: `/categories/detail-student`; params?: Router.UnknownInputParams; } | { pathname: `/categories/detail-teacher`; params?: Router.UnknownInputParams; } | { pathname: `/categories/groups`; params?: Router.UnknownInputParams; } | { pathname: `/courses/add-student`; params?: Router.UnknownInputParams; } | { pathname: `/courses/add-teacher`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/activity-list`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/add-activity`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/assessment-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/evaluation-form`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/results`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/categories/add-category`; params?: Router.UnknownOutputParams; } | { pathname: `/categories/detail-student`; params?: Router.UnknownOutputParams; } | { pathname: `/categories/detail-teacher`; params?: Router.UnknownOutputParams; } | { pathname: `/categories/groups`; params?: Router.UnknownOutputParams; } | { pathname: `/courses/add-student`; params?: Router.UnknownOutputParams; } | { pathname: `/courses/add-teacher`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/activities/activity-list${`?${string}` | `#${string}` | ''}` | `/activities/add-activity${`?${string}` | `#${string}` | ''}` | `/activities/assessment-detail${`?${string}` | `#${string}` | ''}` | `/activities/evaluation-form${`?${string}` | `#${string}` | ''}` | `/activities/results${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/categories/add-category${`?${string}` | `#${string}` | ''}` | `/categories/detail-student${`?${string}` | `#${string}` | ''}` | `/categories/detail-teacher${`?${string}` | `#${string}` | ''}` | `/categories/groups${`?${string}` | `#${string}` | ''}` | `/courses/add-student${`?${string}` | `#${string}` | ''}` | `/courses/add-teacher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/activities/activity-list`; params?: Router.UnknownInputParams; } | { pathname: `/activities/add-activity`; params?: Router.UnknownInputParams; } | { pathname: `/activities/assessment-detail`; params?: Router.UnknownInputParams; } | { pathname: `/activities/evaluation-form`; params?: Router.UnknownInputParams; } | { pathname: `/activities/results`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/categories/add-category`; params?: Router.UnknownInputParams; } | { pathname: `/categories/detail-student`; params?: Router.UnknownInputParams; } | { pathname: `/categories/detail-teacher`; params?: Router.UnknownInputParams; } | { pathname: `/categories/groups`; params?: Router.UnknownInputParams; } | { pathname: `/courses/add-student`; params?: Router.UnknownInputParams; } | { pathname: `/courses/add-teacher`; params?: Router.UnknownInputParams; };
    }
  }
}
